name: mlflow-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - numpy
  - scikit-learn
  - xgboost
  - matplotlib
  - pip:
      - pandas
      - imbalanced-learn
      - mlflow==2.19.0
