name: mlflow-env
channels:
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - pandas
      - scikit-learn
      - xgboost
      - imbalanced-learn
      - mlflow==2.19.0
      - matplotlib
